spring:
  application:
    name: green-uni
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${DATASOURCE.DB_URL}
    username: ${DATASOURCE.USERNAME}
    password: ${DATASOURCE.PASSWORD}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

constants:
  jwt:
    issuer: ${JWT.ISSUER}
    bearer-format: JWT

    claim-key: signedMember
    secret-key: ${JWT.SECRET_KEY}

    access-token-cookie-name: access-token
    access-token-cookie-path: /
    access-token-cookie-validity-seconds: 86_400
    access-token-validity-milliseconds: 86_400_000 # TODO: 배포 전 900_000(15분)으로 변경

    refresh-token-cookie-name: refresh-token
    refresh-token-cookie-path: /api/member/reissue
    refresh-token-cookie-validity-seconds: 1_296_000 #15일
    refresh-token-validity-milliseconds: 1_296_000_000 #15일
  file:
    directory: ${FILE.DIRECTORY}